version: 2
jobs:
  test:
    parallelism: 2
    working_directory: ~/app
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
        environment:
          RAILS_ENV: test
          DATABASE_URL: postgresql://ubuntu@localhost/circle_test?sslmode=disable
      - image: postgres:9.6.2
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - restore_cache:
          key: v1-ruby-dependencies-{{ checksum "Gemfile.lock" }}
      - run: gem install bundler
      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=$(nproc) --retry=3
      - run: mv config/database.ci.yml config/database.yml
      - run: cp .env.example .env
      - run: bundle exec rake db:create db:schema:load --trace
      - save_cache:
          key: v1-ruby-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Tests
          command: |
            bundle exec rspec --profile 10 \
                              --out /tmp/test-results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - store_test_results:
          path: /tmp/test-results

workflows:
  version: 2
  test_and_pronto:
    jobs:
      - test
