default: &defaults
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: <%= ENV['POSTGRES_HOST'] %>

development:
  <<: *defaults
  database: rms_development

test:
  adapter: postgresql
  encoding: unicode
  <<: *defaults
  database: rms_test
  pool: 5

production:
  <<: *defaults
  database: rms_production