default: &defaults
  adapter: postgresql
  encoding: unicode
  username: FAR-wtag
  password: asd123
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: <%= ENV['POSTGRES_HOST'] %>

development:
  <<: *defaults
  database: <%= ENV['POSTGRES_DB'] %>

test:
  <<: *defaults
  database: <%= ENV['POSTGRES_TEST_DB'] %>

production:
  <<: *defaults
  database: <%= ENV['POSTGRES_DB'] %>
